-- MOVIE 테이블
CREATE TABLE MOVIE (
    MOVIE_NAME VARCHAR(100), 
    MOVIE_RATING VARCHAR(20), 
    MOVIE_TYPE VARCHAR(20), 
    MOVIE_PRODUCER VARCHAR(50), 
    MOVIE_PERFORMER VARCHAR(300), 
    MOVIE_RELEASEDATE DATE, 
    MOVIE_OVERVIEW VARCHAR(4000), 
    MOVIE_POSTER VARCHAR(2000), 
    MOVIE_STATUS VARCHAR(50), 
    MOVIE_ID VARCHAR(50), 
    PRIMARY KEY (MOVIE_ID)
);

-- SCREEN 테이블
CREATE TABLE SCREEN (
    SCREEN_ID VARCHAR(20), 
    SCREEN_NAME VARCHAR(10), 
    SCREEN_TYPE VARCHAR(20), 
    SCREEN_TOTAL_SEATS INT, 
    PRIMARY KEY (SCREEN_ID)
);

-- SCHEDULE 테이블
CREATE TABLE SCHEDULE (
    SCHEDULE_ID VARCHAR(20), 
    SCHEDULE_DATE DATE NOT NULL, 
    SHOW_TIME VARCHAR(20) NOT NULL, 
    MOVIE_ID VARCHAR(20) NOT NULL, 
    SCREEN_ID VARCHAR(10) NOT NULL, 
    PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT FK_MOVIE FOREIGN KEY (MOVIE_ID)
        REFERENCES MOVIE (MOVIE_ID), 
    CONSTRAINT FK_SCREEN FOREIGN KEY (SCREEN_ID)
        REFERENCES SCREEN (SCREEN_ID)
);

--TICKET 테이블
CREATE TABLE TICKET (
    TICKET_ID VARCHAR2(20) PRIMARY KEY,        
    SCHEDULE_ID VARCHAR2(20),                  
    CUSTOMER_NAME VARCHAR2(20),                
    CUSTOMER_PHONE VARCHAR2(20),               
    CUSTOMER_COUNT NUMBER,                    
    SELECT_SEATS VARCHAR2(50),                
    PAYMENT VARCHAR2(20),                      
    
    CONSTRAINT FK_SCHEDULE_ID FOREIGN KEY (SCHEDULE_ID)
        REFERENCES SCHEDULE (SCHEDULE_ID)     
);
